"""Generate the FIGS analysis notebooks as .ipynb files.

Run once: ``python notebooks/_build_notebooks.py``. Produces:
  01_case_analysis.ipynb      — run/load a forecast, SPC-style maps, overlay reports
  02_training_progress.ipynb  — dataset/class balance, per-band/hazard val metrics, calibration
  03_feature_dependence.ipynb — permutation importance + partial dependence
  04_csi_accuracy.ipynb       — performance diagram (POD/SR/CSI), reliability, AUC/AUPRC
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


_CID = [0]


def _id():
    _CID[0] += 1
    return f"c{_CID[0]:03d}"


def md(*lines):
    return {"cell_type": "markdown", "id": _id(), "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {"cell_type": "code", "id": _id(), "metadata": {}, "execution_count": None,
            "outputs": [], "source": _src(lines)}


def _src(lines):
    out = []
    for i, ln in enumerate(lines):
        out.append(ln + ("\n" if i < len(lines) - 1 else ""))
    return out


def nb(*cells):
    return {
        "cells": list(cells),
        "metadata": {
            "kernelspec": {"display_name": "Python 3 (met)", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


SETUP = code(
    "# Run with the `met` conda env kernel.",
    "%load_ext autoreload",
    "%autoreload 2          # pick up edits to figs/ without restarting the kernel",
    "import warnings; warnings.filterwarnings('ignore')",
    "import sys, numpy as np, pandas as pd, matplotlib.pyplot as plt",
    "sys.path.insert(0, '..')   # so `import figs` works from notebooks/",
    "from figs import config as C",
)

# --------------------------------------------------------------------------- #
# 01 — case analysis
# --------------------------------------------------------------------------- #
case = nb(
    md("# FIGS — Case Analysis & Display",
       "",
       "Run (or load) a forecast for a HRRR cycle, render SPC-style probability /",
       "categorical / median-intensity maps, and overlay the observed storm reports."),
    SETUP,
    code("from datetime import datetime, timezone, timedelta",
         "from figs.model.predict import predict_forecast",
         "from figs.products import plots, summary, cig, netcdf",
         "from figs.data import reports, grid",
         "",
         "RUN   = datetime(2023, 4, 19, 18, tzinfo=timezone.utc)  # HRRR cycle to forecast",
         "FXX   = list(range(1, 13))                              # forecast hours",
         "HAZARD = 'tor'                                          # 'tor' | 'wind' | 'hail'",
         "MODELS = None                                           # None -> Data/models",
         "DL_WORKERS = 8                                          # forecast hours downloaded concurrently"),
    md("## Predict (or load a prepared netCDF)"),
    code("try:",
         "    preds = predict_forecast(RUN, FXX, models_dir=MODELS, max_members=6, workers=DL_WORKERS)",
         "    print('predicted', len(preds), 'forecast hours')",
         "except Exception as e:",
         "    print('predict failed (need trained models?):', e)",
         "    preds = None"),
    md("## Map extent",
       "",
       "Plan-view extent `[lon_min, lon_max, lat_min, lat_max]` for ALL plots below — kept",
       "in its own cell AFTER predict so you can re-tune the zoom and re-run just the plots",
       "without re-forecasting. `None` lets cartopy auto-fit the FIGS grid."),
    code("MAP_EXTENT = [-110, -80, 25, 55]",
         "plots.set_extent(MAP_EXTENT)"),
    md("## Per-forecast-hour SPC-style probability map"),
    code("FH = 6  # forecast hour to display",
         "if preds:",
         "    p = preds[FH][f'p_{HAZARD}']",
         "    dist = np.nan_to_num(preds[FH][f'dist_{HAZARD}'])",
         "    risk = cig.categorical_risk(HAZARD, p*100, dist)",
         "    plots.plot_probability(p, HAZARD, f'{HAZARD} p f{FH:02d} {RUN:%Y-%m-%d %HZ}', '/tmp/_p.png')",
         "    plots.plot_categorical(risk['category'], HAZARD, f'{HAZARD} categorical f{FH:02d}', '/tmp/_c.png')",
         "    from IPython.display import Image, display",
         "    display(Image('/tmp/_p.png')); display(Image('/tmp/_c.png'))"),
    md("## Day-total (cumulative) risk + median intensity",
       "",
       "The cumulative daily **categorical** outlook is ALWAYS across all 3 hazards "
       "(the SPC Day-1 categorical = max category over tor/wind/hail). **Day-max** "
       "median conditional-intensity is shown for **each** hazard (per-hour median "
       "bin, maxed over hours), masked to that hazard's threat area (day-max prob ≥ "
       "its lowest SPC level)."),
    code("if preds:",
         "    from IPython.display import Image, display",
         "    # cumulative daily CATEGORICAL across ALL hazards (SPC-style Day-1 categorical)",
         "    combined = summary.combined_categorical(preds)",
         "    plots.plot_categorical(combined['category'], 'all', 'cumulative daily categorical (all hazards)', '/tmp/_day.png')",
         "    display(Image('/tmp/_day.png'))",
        "    # day-MAX median conditional-intensity bin for EACH hazard: per-hour",
         "    # median bin, then the element-wise max over hours (strongest median",
         "    # intensity reached anywhere that day). -1 = no mass; masked below.",
         "    for h in C.HAZARDS:",
         "        meds = np.stack([summary.median_intensity_bin(np.nan_to_num(preds[f][f'dist_{h}'])) for f in FXX], axis=0)",
         "        med = meds.max(axis=0)",
         "        daymax_h = summary.day_max({f: preds[f][f'p_{h}'] for f in FXX})",
         "        med = np.where(daymax_h >= C.SPC_PROB_LEVELS[h][0], med, -1)  # threat area only",
         "        plots.plot_intensity(med, h, f'{h} median intensity (threat area, day-max)', f'/tmp/_int_{h}.png')",
         "        display(Image(f'/tmp/_int_{h}.png'))"),
    md("## Forecast vs observed reports — overlay on the day-max probability"),
    code("import cartopy.crs as ccrs, cartopy.feature as cfeature",
         "from figs.data.grid import figs_xy, lcc_forward, figs_latlon",
         "day = RUN.replace(hour=0)  # convective-day label / SPC archive date",
         "# Observed reports over the FORECAST VALID WINDOW (RUN+min..max FXX). An evening",
         "# event spills past 00Z into the next UTC day, so fetch every UTC day it spans",
         "# and filter to the window — a 00Z-00Z calendar fetch would miss those reports.",
         "v0 = RUN + timedelta(hours=min(FXX)); v1 = RUN + timedelta(hours=max(FXX))",
         "udays = sorted({v0.replace(hour=0,minute=0,second=0,microsecond=0),",
         "                v1.replace(hour=0,minute=0,second=0,microsecond=0)})",
         "rep_all = pd.concat([reports.reports_for_day(d) for d in udays], ignore_index=True)",
         "rep_all = rep_all[(rep_all.time >= v0) & (rep_all.time <= v1)]",
         "rep = rep_all[rep_all.hazard == HAZARD].copy()",
         "print(len(rep), HAZARD, 'reports in valid window', f'{v0:%Y-%m-%d %HZ}', '->', f'{v1:%Y-%m-%d %HZ}')",
         "lat, lon = figs_latlon()",
         "daymax = summary.day_max({f: preds[f][f'p_{HAZARD}'] for f in FXX}) if preds else None",
         "levels = list(C.SPC_PROB_LEVELS[HAZARD]) + [1.0]",
         "fig = plt.figure(figsize=(11,7)); ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=-97.5, central_latitude=38.5))",
         "ax.add_feature(cfeature.STATES, lw=0.3)",
         "if MAP_EXTENT: ax.set_extent(MAP_EXTENT)",
         "if daymax is not None:",
         "    cf = ax.contourf(lon, lat, daymax, levels=levels, colors=plots.PROB_COLORS[HAZARD],",
         "                     transform=ccrs.PlateCarree(), alpha=0.85, extend='neither')",
         "    plt.colorbar(cf, ax=ax, orientation='horizontal', pad=0.03, shrink=0.8, ticks=C.SPC_PROB_LEVELS[HAZARD])",
         "ax.scatter(rep.lon, rep.lat, s=18, c='black', marker='x', lw=0.8, transform=ccrs.PlateCarree(), label=f'observed {HAZARD}')",
         "ax.set_title(f'FIGS day-max p({HAZARD}) vs observed reports — valid {v0:%m-%d %HZ}–{v1:%m-%d %HZ}'); ax.legend(loc='lower right'); plt.show()"),
    md("### Capture: what fraction of observed reports fell inside each probability contour?"),
    code("if preds is not None and len(rep):",
         "    xc, yc = figs_xy(); x, y = lcc_forward(rep.lon.values, rep.lat.values)",
         "    ix = np.round((x-xc[0])/(xc[1]-xc[0])).astype(int); iy = np.round((y-yc[0])/(yc[1]-yc[0])).astype(int)",
         "    ok = (ix>=0)&(ix<len(xc))&(iy>=0)&(iy<len(yc))",
         "    pvals = daymax[iy[ok], ix[ok]]",
         "    print(f'{ok.sum()} in-domain reports | median forecast prob at report sites = {np.median(pvals):.3f}')",
         "    for thr in C.SPC_PROB_LEVELS[HAZARD]:",
         "        print(f'  captured at >= {int(thr*100):>2d}%: {100*(pvals>=thr).mean():5.1f}% of reports')",
         "    # crude reliability for the day: report frequency vs forecast prob bin",
         "    from figs.model.calibrate import reliability",
         "    # (skipped here; see 02_training_progress for full reliability)"),
    md("### Observed vs predicted conditional intensity"),
    code("if preds is not None and len(rep):",
         "    from figs.data.labels import intensity_bin",
         "    labels = C.INTENSITY_BINS[HAZARD]['labels']; nb = len(labels)",
         "    # observed intensity histogram (EF for tor; exclude EFU=-1)",
         "    vals = rep.ef.values if HAZARD=='tor' else rep.magnitude.values",
         "    obs = np.zeros(nb)",
         "    for v in vals:",
         "        b = intensity_bin(HAZARD, v)",
         "        if b>=0: obs[b]+=1",
         "    obs = obs/obs.sum() if obs.sum() else obs",
         "    # predicted mean conditional distribution over the threat area (p>=5%)",
         "    dist_day = np.nanmean([np.nan_to_num(preds[f][f'dist_{HAZARD}']) for f in FXX], axis=0)  # (nb,ny,nx)",
         "    mask = daymax >= 0.05",
         "    pred = dist_day[:, mask].mean(axis=1) if mask.any() else np.full(nb, np.nan)",
         "    pred = pred/pred.sum()",
         "    xpos = np.arange(nb); w=0.4",
         "    fig, ax = plt.subplots(figsize=(8,4))",
         "    ax.bar(xpos-w/2, obs, w, label='observed'); ax.bar(xpos+w/2, pred, w, label='predicted (threat area)')",
         "    ax.set_xticks(xpos); ax.set_xticklabels(labels); ax.set_ylabel('frequency'); ax.legend()",
         "    ax.set_title(f'{HAZARD} conditional intensity: observed vs predicted'); plt.show()"),
    md("## 6-panel: FIGS prob+CIG vs SPC outlooks (tornado / wind / hail)",
       "",
       "Top row = FIGS day-max probability (SPC colors) with significant (CIG≥2) hatching;",
       "bottom row = the **actual SPC Day-1 probabilistic outlook contours**, pulled as",
       "vectors from the IEM GIS archive and drawn on the same projection (significant-",
       "severe area hatched). The issuance closest to RUN is used."),
    code("import cartopy.crs as ccrs, cartopy.feature as cfeature",
         "from figs.products import cig as cigmod, spc",
         "lat, lon = figs_latlon()",
         "# actual SPC outlook contours from IEM (vector), selected to the run's issuance",
         "spc_gdf = None",
         "try:",
         "    spc_gdf = spc.select_issuance(spc.fetch_spc_outlooks(RUN, day=1), RUN)",
         "except Exception as e:",
         "    print('SPC outlook fetch failed:', e)",
         "spc_iss = (sorted(spc_gdf['ISSUE'].unique())[0] if spc_gdf is not None and len(spc_gdf) else 'n/a')",
         "proj = ccrs.LambertConformal(central_longitude=-97.5, central_latitude=38.5)",
         "fig = plt.figure(figsize=(16,8))",
         "for j, h in enumerate(['tor','wind','hail']):",
         "    ax = fig.add_subplot(2, 3, j+1, projection=proj)",
         "    ax.add_feature(cfeature.STATES, lw=0.3)",
         "    if MAP_EXTENT: ax.set_extent(MAP_EXTENT)",
         "    if preds:",
         "        dmax = summary.day_max({f: preds[f][f'p_{h}'] for f in FXX})",
         "        lv = list(C.SPC_PROB_LEVELS[h]) + [1.0]",
         "        ax.contourf(lon, lat, dmax, levels=lv, colors=plots.PROB_COLORS[h], transform=ccrs.PlateCarree(), extend='neither')",
        "        # CIG derived HOUR-BY-HOUR (per-hour conditional dist), then maxed over",
         "        # hours — matches summary.cumulative_categorical. Averaging the dist first",
         "        # would dilute the upper tail and understate peak severity.",
         "        cigmax = np.stack([cigmod.derive_cig_category(h, np.nan_to_num(preds[f][f'dist_{h}'])) for f in FXX], axis=0).max(axis=0)",
         "        cigcat = np.where(dmax >= C.SPC_PROB_LEVELS[h][0], cigmax, 0)",
         "        plots.overlay_cig(ax, lon, lat, cigcat)  # CIG1 dots / CIG2 diag / CIG3 cross, masked to prob area",
         "    ax.set_title(f'FIGS {h}')",
         "    ax2 = fig.add_subplot(2, 3, j+4, projection=proj)",
         "    ax2.add_feature(cfeature.STATES, lw=0.3)",
         "    if MAP_EXTENT: ax2.set_extent(MAP_EXTENT)",
         "    spc.plot_spc_outlook(ax2, spc_gdf, h, plots.PROB_COLORS[h])  # filled by prob threshold + SIGN hatch",
         "    ax2.set_title(f'SPC {h} ({spc_iss})')",
         "fig.suptitle(f'FIGS vs SPC Day-1 outlooks — {day:%Y-%m-%d}', y=1.02); plt.tight_layout(); plt.show()"),
    md("## Inspect a saved prediction netCDF"),
    code("# import xarray as xr",
         "# ds = xr.open_dataset(f'../Data/products/figs_{RUN:%Y%m%d_%HZ}.nc'); ds"),
)

# --------------------------------------------------------------------------- #
# 02 — training progress
# --------------------------------------------------------------------------- #
train = nb(
    md("# FIGS — Training Diagnostics",
       "",
       "Dataset composition (split sizes, class balance per hazard/lead band), held-out",
       "validation skill per model, and calibration (reliability) curves.",
       "",
       "mlx-boosting fits in one shot (no per-iteration loss trace); this notebook focuses",
       "on the validation-set diagnostics that matter for guidance products."),
    SETUP,
    code("from figs.data.dataset import read_dataset, dataset_feature_columns",
         "from figs.model.wrapper import GBDTModel",
         "from figs.model.calibrate import Calibrator, reliability_ci, low_dense_edges",
         "from figs.config import LEAD_BANDS, HAZARDS",
         "from sklearn.metrics import roc_auc_score, average_precision_score",
         "from pathlib import Path",
         "",
         "import json",
         "DATA   = '../Data/processed/figs_v2.parquet'   # MUST be the dataset the models were trained on",
         "MODELS = '../Data/models'",
         "VAL_SAMPLE = 2_000_000  # cap rows pulled per band for skill/reliability",
         "",
         "# Feature list comes from the MODELS' own feature_cols.json (written at train",
         "# time) so it always matches what the models expect, in the right order. DATA",
         "# must be the parquet those models were trained on (else the columns won't line",
         "# up -> the '778 vs 5086 features' error). We never load the full feature set:",
         "# counts use only the small label/split/fxx columns.",
         "feats = json.loads((Path(MODELS)/'feature_cols.json').read_text())",
         "missing = [c for c in feats if c not in set(dataset_feature_columns(DATA))]",
         "if missing:",
         "    raise ValueError(f'{len(missing)} model features absent from DATA (e.g. {missing[:3]}); '",
         "                     f'point DATA at the dataset these models were trained on')",
         "label_cols = list(HAZARDS) + [h+'_sig' for h in HAZARDS]",
         "meta = read_dataset(DATA, columns=label_cols + ['split','fxx'])",
         "print(f'{len(meta):,} rows | {len(feats)} model features (from feature_cols.json)')"),
    md("## Split sizes and class balance (metadata only)"),
    code("print(meta.split.value_counts())",
         "for h in HAZARDS:",
         "    print(f'{h:5s} positives: {100*meta[h].mean():.3f}%% ({meta[h].sum():,})  sig: {meta[h+\"_sig\"].sum():,}')"),
    md("## Positive rate by lead band and hazard"),
    code("if 'fxx' in meta:",
         "    rows = []",
         "    for b in LEAD_BANDS:",
         "        sub = meta[(meta.fxx>=b.fmin)&(meta.fxx<=b.fmax)]",
         "        rows.append({'band': b.name, **{h: round(100*sub[h].mean(),3) for h in HAZARDS}, 'n': len(sub)})",
         "    display(pd.DataFrame(rows))"),
    md("## Held-out validation skill per hazard × band (streamed, sampled per band)"),
    code("def load_split(b, cols, split='validation'):",
         "    f = [('fxx','>=',b.fmin), ('fxx','<=',b.fmax), ('split','==',split)]",
         "    d = read_dataset(DATA, filters=f, columns=cols)",
         "    return d.sample(VAL_SAMPLE, random_state=0) if len(d) > VAL_SAMPLE else d",
         "",
         "rows = []",
         "for b in LEAD_BANDS:",
         "    va = load_split(b, feats + list(HAZARDS))",
         "    if len(va) == 0: continue",
         "    Xva = va[feats].to_numpy('float32')",
         "    for h in HAZARDS:",
         "        mp = Path(MODELS)/f'hazard_{h}_{b.name}.pkl'",
         "        if not mp.exists() or va[h].nunique()<2: continue",
         "        p = GBDTModel.load(mp).predict_pos(Xva)",
         "        cp = Path(MODELS)/f'calib_{h}_{b.name}.pkl'",
         "        if cp.exists(): p = Calibrator.load(cp).transform(p)",
         "        y = va[h].to_numpy(int)",
        "        rows.append({'hazard':h,'band':b.name,'AUC':round(roc_auc_score(y,p),3),",
         "                     'AUPRC':round(average_precision_score(y,p),3),'n':len(va),'pos':int(y.sum())})",
         "    del va, Xva  # free this band before the next",
         "skill = pd.DataFrame(rows)",
         "display(skill)"),
    md("## AUC / AUPRC vs lead band, by hazard",
       "",
       "How each hazard's skill changes with forecast lead. The dashed/dotted lines are the",
       "published **nadocast (NC 12Z)** and **SPC (1630Z)** HREF-only ROC-AUC benchmarks",
       "(155 days, 2019/1–2022/5) as a reference. Note those are whole-forecast AUCs, so they",
       "compare most directly to our short-lead bands."),
    code("# nadocast NC 12Z / SPC 1630Z HREF-only AUC benchmarks (155 days, 2019-2022)",
         "REFERENCE_AUC = {'tor':  {'NC': 0.899, 'SPC': 0.888},",
         "                 'wind': {'NC': 0.923, 'SPC': 0.889},",
         "                 'hail': {'NC': 0.916, 'SPC': 0.892}}",
         "order = [b.name for b in LEAD_BANDS if b.name in set(skill.band)]",
         "fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))",
         "for metric, ax in zip(['AUC', 'AUPRC'], axes):",
         "    for h in HAZARDS:",
         "        s = skill[skill.hazard == h].set_index('band').reindex(order)",
         "        line, = ax.plot(range(len(order)), s[metric], 'o-', label=h)",
         "        if metric == 'AUC':",
         "            c = line.get_color()",
         "            ax.axhline(REFERENCE_AUC[h]['NC'], color=c, ls='--', lw=1, alpha=0.7)",
         "            ax.axhline(REFERENCE_AUC[h]['SPC'], color=c, ls=':', lw=1, alpha=0.7)",
         "    ax.set_xticks(range(len(order))); ax.set_xticklabels(order, rotation=45, ha='right')",
         "    ax.set_xlabel('lead band'); ax.set_ylabel(metric); ax.grid(alpha=0.3); ax.legend()",
         "axes[0].axhline(0.5, color='gray', ls='-', lw=0.5)  # AUC no-skill",
         "axes[0].plot([], [], 'k--', label='nadocast NC 12Z'); axes[0].plot([], [], 'k:', label='SPC 1630Z')",
         "axes[0].legend(fontsize=8, loc='lower left')",
         "axes[0].set_title('AUC by lead band (-- nadocast NC, : SPC benchmark)')",
         "axes[1].set_title('AUPRC by lead band')",
         "plt.tight_layout(); plt.show()"),
    md("## Validation positives per band (skill is noisier where positives are few)"),
    code("piv = skill.pivot_table(index='band', columns='hazard', values='pos').reindex(order)",
         "piv.plot.bar(figsize=(11,4)); plt.ylabel('validation positives'); plt.yscale('log')",
         "plt.title('positive count by band x hazard'); plt.tight_layout(); plt.show()",
         "display(piv)"),
    md("## Reliability (calibration) curves — all-band ensemble, held-out TEST split, weighted",
       "",
       "Replicates what `predict_valid` actually ships: every forecast hour averages the",
       "**calibrated** predictions of **all** trained lead-band models (a lead-diverse ensemble).",
       "We do the same here — apply every band's model to the test rows and average — instead of",
       "scoring a single band. Averaging 8 independently-clustered tree ensembles fills in the gaps",
       "between leaf values, so the operational curve is far smoother than any one band's.",
       "",
       "Evaluated on the **test** split (calibrators were fit on *validation*, so scoring them on",
       "validation would be circular), **weighted** by the subsample-reweighting weights so",
       "'observed freq' is the TRUE climatological rate. A calibrated curve should hug the diagonal.",
       "The number above each calibrated point is that bin's positive count (drives CI width)."),
    code("# Per-hazard binning/range: tor has ~10x fewer positives -> custom edges",
         "# matched to SPC tor levels (fine at the bottom); wind/hail denser to 0.8.",
         "REL_EDGES = {'tor':  np.array([0, 0.02, 0.05, 0.10, 0.15, 0.30, 0.45]),",
         "             'wind': low_dense_edges(n_low=12, n_high=6, split=0.20),",
         "             'hail': low_dense_edges(n_low=12, n_high=6, split=0.20)}",
         "REL_XMAX = {'tor': 0.45, 'wind': 0.8, 'hail': 0.8}",
         "",
         "# Evaluate on a representative test sample (one band's test rows); the labels are",
         "# valid-time occurrence, and every band model is applied to them just as in production.",
         "b = LEAD_BANDS[0]",
         "te = load_split(b, feats + list(HAZARDS) + ['weight'], split='test')",
         "Xte = te[feats].to_numpy('float32'); w = te['weight'].to_numpy('float32')",
         "",
         "def ensemble_preds(h):",
         "    '''All-band ensemble (raw, calibrated) for hazard h on Xte, matching predict_valid.'''",
         "    tags = [bb.name for bb in LEAD_BANDS if (Path(MODELS)/f'hazard_{h}_{bb.name}.pkl').exists()]",
         "    raw_stack, cal_stack = [], []",
         "    for tag in tags:",
         "        pm = GBDTModel.load(Path(MODELS)/f'hazard_{h}_{tag}.pkl').predict_pos(Xte)",
         "        raw_stack.append(pm)",
         "        cp = Path(MODELS)/f'calib_{h}_{tag}.pkl'",
         "        cal_stack.append(Calibrator.load(cp).transform(pm) if cp.exists() else pm)",
         "    if not raw_stack: return None, None, tags",
         "    return np.mean(raw_stack, axis=0), np.mean(cal_stack, axis=0), tags",
         "",
         "fig, axes = plt.subplots(1, 3, figsize=(14,4))",
         "for ax,h in zip(axes, HAZARDS):",
         "    p, pc, tags = ensemble_preds(h)",
         "    if p is None or te[h].nunique()<2:",
         "        ax.set_title(f'{h}: n/a'); continue",
         "    y = te[h].to_numpy(int)",
         "    for label,pp in [('raw',p),('calibrated',pc)]:",
         "        mb,ob,lo,hi,_,npos = reliability_ci(pp, y, sample_weight=w, edges=REL_EDGES[h], n_boot=300)",
         "        line, = ax.plot(mb, ob, 'o-', label=label)",
         "        ax.fill_between(mb, lo, hi, color=line.get_color(), alpha=0.2)  # 95% bootstrap CI",
         "        if label=='calibrated':  # annotate # of positives per bin (drives CI width)",
         "            for x,yv,nn in zip(mb,ob,npos):",
         "                ax.annotate(f'{nn}', (x,yv), textcoords='offset points', xytext=(0,5),",
         "                            ha='center', fontsize=6, color=line.get_color())",
         "    ax.plot([0,1],[0,1],'k--',lw=0.7); ax.set_xlabel('forecast prob'); ax.set_ylabel('observed freq (weighted)')",
         "    ax.set_xlim(0, REL_XMAX[h]); ax.set_ylim(0, REL_XMAX[h])  # tor 0-0.45, wind/hail 0-0.8",
         "    ax.set_title(f'{h} reliability ({len(tags)}-band ens, test, 95% CI)'); ax.legend()",
         "plt.tight_layout(); plt.show()"),
)

# --------------------------------------------------------------------------- #
# 03 — feature dependence
# --------------------------------------------------------------------------- #
feat = nb(
    md("# FIGS — Feature Dependence",
       "",
       "Model-agnostic **permutation importance** (AUC drop when a feature column is",
       "shuffled) and **partial-dependence** curves for the top features. Works with the",
       "mlx-boosting wrapper without needing native importances."),
    SETUP,
    code("from figs.data.dataset import read_dataset, feature_columns",
         "from figs.model.wrapper import GBDTModel",
         "from figs.config import LEAD_BANDS",
         "from sklearn.metrics import roc_auc_score",
         "from pathlib import Path",
         "",
         "import json",
         "DATA='../Data/processed/figs_v2.parquet'; MODELS='../Data/models'  # DATA must match the models",
         "HAZARD='tor'; BAND=LEAD_BANDS[0].name",
         "# feature list/order from the models' feature_cols.json (matches what they expect)",
         "feats = json.loads((Path(MODELS)/'feature_cols.json').read_text())",
         "df = read_dataset(DATA)  # NOTE: loads the full matrix; heavy at ~5k features",
         "missing = [c for c in feats if c not in df.columns]",
         "if missing: raise ValueError(f'{len(missing)} model features absent from DATA; point DATA at the models\\' training set')",
         "va = df[df.split=='validation']",
         "if 'fxx' in va:",
         "    b=[x for x in LEAD_BANDS if x.name==BAND][0]; va=va[(va.fxx>=b.fmin)&(va.fxx<=b.fmax)]",
         "va = va.sample(min(len(va), 40000), random_state=0)   # subsample for speed",
         "m = GBDTModel.load(Path(MODELS)/f'hazard_{HAZARD}_{BAND}.pkl')",
         "X = va[feats].to_numpy('float32'); y = va[HAZARD].to_numpy(int)",
         "base = roc_auc_score(y, m.predict_pos(X)); print('baseline AUC', round(base,4))"),
    md("## Permutation importance (top 25)"),
    code("rng = np.random.default_rng(0)",
         "imp = {}",
         "for j,f in enumerate(feats):",
         "    Xp = X.copy(); Xp[:,j] = rng.permutation(Xp[:,j])",
         "    imp[f] = base - roc_auc_score(y, m.predict_pos(Xp))",
         "    if j % 100 == 0: print(f'{j}/{len(feats)}')",
         "imp = pd.Series(imp).sort_values(ascending=False)",
         "imp.head(25).iloc[::-1].plot.barh(figsize=(7,8)); plt.xlabel('AUC drop'); plt.title(f'{HAZARD} {BAND} permutation importance'); plt.show()",
         "imp.head(25)"),
    md("## Partial dependence for the top features"),
    code("top = imp.head(6).index.tolist()",
         "fig, axes = plt.subplots(2,3, figsize=(15,8))",
         "for ax,f in zip(axes.ravel(), top):",
         "    j = feats.index(f)",
         "    grid_vals = np.nanpercentile(X[:,j], np.linspace(2,98,20))",
         "    pd_curve = []",
         "    for g in grid_vals:",
         "        Xt = X.copy(); Xt[:,j] = g; pd_curve.append(m.predict_pos(Xt).mean())",
         "    ax.plot(grid_vals, pd_curve, 'o-'); ax.set_title(f); ax.set_ylabel('mean p')",
         "plt.tight_layout(); plt.show()"),
)

# --------------------------------------------------------------------------- #
# 04 — CSI / accuracy
# --------------------------------------------------------------------------- #
csi = nb(
    md("# FIGS — CSI / Accuracy Verification",
       "",
       "Performance diagram (POD vs success ratio with CSI/bias contours), threshold sweep",
       "of CSI/POD/FAR, and AUC/AUPRC — on the held-out **test** split, per hazard."),
    SETUP,
    code("from figs.data.dataset import read_dataset, feature_columns",
         "from figs.model.wrapper import GBDTModel",
         "from figs.model.calibrate import Calibrator",
         "from figs.config import LEAD_BANDS, HAZARDS",
         "from sklearn.metrics import roc_auc_score, average_precision_score",
         "from pathlib import Path",
         "",
         "import json",
         "DATA='../Data/processed/figs_v2.parquet'; MODELS='../Data/models'  # DATA must match the models",
         "feats = json.loads((Path(MODELS)/'feature_cols.json').read_text())",
         "df = read_dataset(DATA)  # NOTE: loads the full matrix; heavy at ~5k features",
         "missing = [c for c in feats if c not in df.columns]",
         "if missing: raise ValueError(f'{len(missing)} model features absent from DATA; point DATA at the models\\' training set')",
         "te = df[df.split=='test']; print('test rows', len(te))"),
    code("def predict_split(h, sub):",
         "    \"\"\"Calibrated p(h) averaged across covering bands.\"\"\"",
         "    P = np.zeros(len(sub)); n = np.zeros(len(sub))",
         "    X = sub[feats].to_numpy('float32')",
         "    for b in LEAD_BANDS:",
         "        mp = Path(MODELS)/f'hazard_{h}_{b.name}.pkl'",
         "        if not mp.exists(): continue",
         "        mask = ((sub.fxx>=b.fmin)&(sub.fxx<=b.fmax)).to_numpy() if 'fxx' in sub else np.ones(len(sub),bool)",
         "        if not mask.any(): continue",
         "        p = GBDTModel.load(mp).predict_pos(X[mask])",
         "        cp = Path(MODELS)/f'calib_{h}_{b.name}.pkl'",
         "        if cp.exists(): p = Calibrator.load(cp).transform(p)",
         "        P[mask] += p; n[mask] += 1",
         "    return np.divide(P, n, out=np.zeros_like(P), where=n>0)"),
    md("## Contingency metrics across probability thresholds"),
    code("def sweep(p, y, thr=np.linspace(0.01,0.6,30)):",
         "    rows=[]",
         "    for t in thr:",
         "        pred = p>=t; hit=(pred&(y==1)).sum(); fa=(pred&(y==0)).sum(); miss=((~pred)&(y==1)).sum()",
         "        pod = hit/max(hit+miss,1); far = fa/max(hit+fa,1); sr = 1-far",
         "        csi = hit/max(hit+miss+fa,1); bias=(hit+fa)/max(hit+miss,1)",
         "        rows.append(dict(thr=t,POD=pod,SR=sr,FAR=far,CSI=csi,bias=bias))",
         "    return pd.DataFrame(rows)",
         "",
         "sweeps={}",
         "for h in HAZARDS:",
         "    p = predict_split(h, te); y = te[h].to_numpy(int)",
         "    if y.sum()==0: continue",
         "    sweeps[h]=sweep(p,y)",
         "    print(f'{h}: AUC %.3f  AUPRC %.3f  maxCSI %.3f' % (roc_auc_score(y,p), average_precision_score(y,p), sweeps[h].CSI.max()))"),
    md("## Performance diagram (POD vs success ratio; CSI shaded, bias dashed)"),
    code("fig, ax = plt.subplots(figsize=(7,7))",
         "sr = np.linspace(0.001,1,200); pod = np.linspace(0.001,1,200)",
         "SR,POD = np.meshgrid(sr,pod); CSI = 1/(1/SR + 1/POD - 1)",
         "cf = ax.contourf(SR,POD,CSI,levels=np.arange(0,1.01,0.1),cmap='Blues',alpha=0.6)",
         "plt.colorbar(cf,label='CSI')",
         "for bval in [0.5,1,1.5,2,3]:",
         "    ax.plot(sr, bval*sr, 'k--', lw=0.6); ax.text(0.95, min(bval*0.95,0.98), f'{bval}', fontsize=8)",
         "for h,s in sweeps.items():",
         "    ax.plot(s.SR, s.POD, 'o-', ms=3, label=h)",
         "ax.set_xlim(0,1); ax.set_ylim(0,1); ax.set_xlabel('Success Ratio (1-FAR)'); ax.set_ylabel('POD')",
         "ax.set_title('FIGS performance diagram (test split)'); ax.legend(); plt.show()"),
    md("## CSI vs threshold"),
    code("fig,ax=plt.subplots(figsize=(8,5))",
         "for h,s in sweeps.items(): ax.plot(s.thr, s.CSI, label=h)",
         "ax.set_xlabel('probability threshold'); ax.set_ylabel('CSI'); ax.legend(); ax.set_title('CSI vs threshold'); plt.show()"),
)

report_db = nb(
    md("# FIGS — Report Database Overview",
       "",
       "Explore the combined storm-report database (IEM LSRs + SPC daily CSV + SVRGIS,",
       "incl. post-survey EF and tornado **tracks**) over the analysis period: counts,",
       "temporal cycles, spatial distribution, intensity distributions vs the FIGS bins,",
       "and how many forecast hours qualify at each `min_reports` threshold.",
       "",
       "Note: the first pass fetches one CSV per day (cached afterwards). Start with a",
       "season; widen `START`/`END` to the full 2020-2023 once cached."),
    SETUP,
    code("from datetime import datetime, timezone, timedelta",
         "from figs.data import reports, grid",
         "from figs.config import INTENSITY_BINS, SEVERE_THRESHOLDS, SIGNIFICANT_THRESHOLDS, REPORTS_CACHE",
         "import glob, os",
         "",
         "# DEFAULT: read only what's ALREADY cached under Data/reports/ (instant, no network).",
         "# Your dataset builds cache every severe day there, so this shows the ingested DB as-is.",
         "USE_CACHE_ONLY = True",
         "",
         "if USE_CACHE_ONLY:",
         "    files = sorted(glob.glob(str(REPORTS_CACHE / 'reports_*.csv')))",
         "    print('cached day-files:', len(files))",
         "    frames = [pd.read_csv(f, parse_dates=['time']) for f in files if os.path.getsize(f) > 0]",
         "else:",
         "    # fetch an explicit window (fetches+caches any missing days)",
         "    START = datetime(2023, 4, 1, tzinfo=timezone.utc)",
         "    END   = datetime(2023, 6, 30, tzinfo=timezone.utc)",
         "    days = pd.date_range(START, END, freq='D', tz='UTC')",
         "    frames = []",
         "    for i, d in enumerate(days):",
         "        try: frames.append(reports.reports_for_day(d.to_pydatetime()))",
         "        except Exception as e: print('skip', d.date(), e)",
         "        if i % 30 == 0: print(f'{i}/{len(days)} days')",
         "",
         "rep = pd.concat(frames, ignore_index=True)",
         "rep['time'] = pd.to_datetime(rep['time'], utc=True)",
         "rep = rep.dropna(subset=['hazard'])",
         "START, END = rep.time.min(), rep.time.max()",
         "print('total reports', len(rep), '| period', START.date(), '->', END.date())"),
    md("## Counts by hazard (severe-filtered, FIGS thresholds)"),
    code("# apply FIGS severe thresholds: tor any, wind>=50kt, hail>=1in",
         "sev = rep[((rep.hazard=='tor')) | ((rep.hazard=='wind')&(rep.magnitude>=SEVERE_THRESHOLDS['wind_kt']))",
         "          | ((rep.hazard=='hail')&(rep.magnitude>=SEVERE_THRESHOLDS['hail_in']))].copy()",
         "print(sev.hazard.value_counts())",
         "print('\\nsignificant:')",
         "print('  tor EF>=2:', int(((sev.hazard=='tor')&(sev.ef>=2)).sum()))",
         "print('  wind>=65kt:', int(((sev.hazard=='wind')&(sev.magnitude>=65)).sum()))",
         "print('  hail>=2in :', int(((sev.hazard=='hail')&(sev.magnitude>=2)).sum()))"),
    md("## Temporal cycles — by month and hour of day (UTC)"),
    code("fig, ax = plt.subplots(1,2, figsize=(14,4))",
         "for h in ['tor','wind','hail']:",
         "    s = sev[sev.hazard==h]",
         "    s.groupby(s.time.dt.month).size().reindex(range(1,13), fill_value=0).plot(ax=ax[0], marker='o', label=h)",
         "    s.groupby(s.time.dt.hour).size().reindex(range(24), fill_value=0).plot(ax=ax[1], marker='o', label=h)",
         "ax[0].set_xlabel('month'); ax[0].set_title('reports by month'); ax[0].legend()",
         "ax[1].set_xlabel('hour UTC'); ax[1].set_title('diurnal cycle'); ax[1].legend()",
         "plt.tight_layout(); plt.show()"),
    md("## Spatial distribution"),
    code("import cartopy.crs as ccrs, cartopy.feature as cfeature",
         "fig = plt.figure(figsize=(12,7)); ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=-97.5, central_latitude=38.5))",
         "ax.add_feature(cfeature.STATES, lw=0.3); ax.set_extent([-120,-74,23,50])",
         "colors = {'tor':'red','wind':'blue','hail':'green'}",
         "for h,c in colors.items():",
         "    s = sev[sev.hazard==h]",
         "    ax.scatter(s.lon, s.lat, s=4, c=c, alpha=0.3, transform=ccrs.PlateCarree(), label=h)",
         "ax.set_title(f'severe reports {START:%Y-%m-%d} to {END:%Y-%m-%d}'); plt.legend(); plt.show()"),
    md("## Intensity distributions vs the FIGS conditional-intensity bins"),
    code("fig, ax = plt.subplots(1,3, figsize=(15,4))",
         "# tornado EF (exclude EFU/-1)",
         "tor = sev[(sev.hazard=='tor')&(sev.ef>=0)]",
         "tor.ef.value_counts().sort_index().plot.bar(ax=ax[0]); ax[0].set_title('tornado EF'); ax[0].set_xlabel('EF')",
         "# wind kt with bin edges",
         "sev[sev.hazard=='wind'].magnitude.plot.hist(bins=40, ax=ax[1]); ax[1].set_title('wind (kt)')",
         "for e in INTENSITY_BINS['wind']['edges']: ax[1].axvline(e, color='k', ls='--', lw=0.6)",
         "# hail inches with bin edges",
         "sev[sev.hazard=='hail'].magnitude.plot.hist(bins=40, ax=ax[2]); ax[2].set_title('hail (in)')",
         "for e in INTENSITY_BINS['hail']['edges']: ax[2].axvline(e, color='k', ls='--', lw=0.6)",
         "plt.tight_layout(); plt.show()"),
    md("## SVRGIS tornado tracks (a chosen day)"),
    code("DAY = datetime(2023, 3, 31, 22, tzinfo=timezone.utc)  # set to a tornado day in your window",
         "tr = reports.svrgis_tracks_in_window(DAY, 180)  # +/- 3 h",
         "print(len(tr), 'tracks')",
         "fig = plt.figure(figsize=(11,7)); ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=-97.5, central_latitude=38.5))",
         "ax.add_feature(cfeature.STATES, lw=0.3); ax.set_extent([-105,-80,30,45])",
         "for _,t in tr.iterrows():",
         "    ax.plot([t.slon,t.elon],[t.slat,t.elat], '-', lw=1+ (t.ef if t.ef>0 else 0),",
         "            color='purple', transform=ccrs.PlateCarree())",
         "ax.set_title(f'SVRGIS tornado tracks near {DAY:%Y-%m-%d %HZ}'); plt.show()"),
    md("## Qualifying forecast hours vs `min_reports` (drives sample/band counts)",
       "",
       "Computed from the loaded (cached) reports — no network. This is the per-band",
       "sample count for a build; multiply by the number of bands for the total."),
    code("# count reports per top-of-hour across all hazards (matches severe_valid_hours)",
         "hourly = rep.groupby(rep.time.dt.floor('h')).size()",
         "for mr in [1,3,5,10,15,20]:",
         "    n = int((hourly >= mr).sum())",
         "    print(f'min_reports={mr:2d} -> {n} valid hours -> {n} samples/band')"),
)

NOTEBOOKS = {
    "01_case_analysis.ipynb": case,
    "05_report_database.ipynb": report_db,
    "02_training_progress.ipynb": train,
    "03_feature_dependence.ipynb": feat,
    "04_csi_accuracy.ipynb": csi,
}

if __name__ == "__main__":
    for name, content in NOTEBOOKS.items():
        path = HERE / name
        path.write_text(json.dumps(content, indent=1))
        print("wrote", path)
